-- UNUSED JUST KEEP IT FOR FUTURE UPDATE
-- David-Kunz/jester
-- require("jester").setup({
--   path_to_jest = "node_modules/.bin/jest",
--   dap = { type = "pwa-node" },
-- })
-- -- require'jester'.setup({ dap = { type = 'pwa-node'}})
-- -- require'jester'.setup({ path_to_jest = "/opt/homebrew/bin/jest", dap = { type = 'pwa-node' } })
-- vim.keymap.set("n", "<leader>tt", function()
--   require("jester").run()
-- end)
-- vim.keymap.set("n", "<leader>tl", function()
--   require("jester").run_last()
-- end)
-- vim.keymap.set("n", "<leader>tf", function()
--   require("jester").run_file()
-- end)
-- vim.keymap.set("n", "<leader>dl", function()
--   require("jester").debug_last()
-- end)
-- vim.keymap.set("n", "<leader>df", function()
--   require("jester").debug_file()
-- end)
-- vim.keymap.set("n", "<leader>dq", function()
--   require("jester").terminate()
-- end)
-- vim.keymap.set("n", "<leader>dd", function()
--   require("jester").debug()
-- end)
